### ISSUE TITLE
Train/Test using the LOL dataset

### ISSUE THREAD

**Issue by by5747** [MohitLamba94/LLPackNet#1]
Hi.
You only released train/test code for SID data.
I wanna train and test your model using the LOL dataset.

Can you open your code for the LOL?

Thank you:)

**Comment by MohitLamba94** [comment]
This should be straightforward. Simply use PIL instead of rawpy to load PNG image.

**Comment by woaiwojia4816294** [comment]
> This should be straightforward. Simply use PIL instead of rawpy to load PNG image.

hello, i use np.array(PIL.Image.open()) to load .png image, but i am a little confused about why the img_loww.shape is two-dimensional (H,W) in your original code. if i use .png format, the img_loww should is (H,W,3) this will make subsequent code error. So how should i deal with lowlight image in .png format, thanks a lot.
`raw = rawpy.imread(self.train_files[idx])
 img = raw.raw_image_visible.astype(np.float32).copy()
 raw.close()`

**Comment by MohitLamba94** [comment]
Since you want to load a PNG image and finally convert to tensor, why dont you use [torchvision.io.read_image](https://pytorch.org/vision/stable/io.html#torchvision.io.read_image) which does all of this one shot. I never faced any issue using it.

Reads a JPEG or PNG image into a 3 dimensional RGB Tensor. Optionally converts the image to the desired format. The values of the output tensor are uint8 between 0 and 255.
