### ISSUE TITLE
where is AVG-sir-amplifier

### ISSUE THREAD

**Issue by love112358** [MohitLamba94/LLPackNet#2]
I didn't find that model in this project

**Comment by MohitLamba94** [comment]
Sorry, it's been a while on this project, and is now obsolete since the newer version is available. Don't remember exactly. But as I can see complete Jupyter Notebooks with Weights are still available at https://github.com/MohitLamba94/LLPackNet/tree/master/ablations and perhaps few modifications may be required.

Please try them or re-train.
